// function handlepromise(resolve,reject){
//     reject("rejected....");
// }
// let Promise = new Promise (handlepromise)
// // console.log();
// promise
//  .then(res => {
//     console.log({res});
// })
// .catch(err =>{
//     console.log({err});
// })

try {
    let a= b+c;
    console.log(a);
}
catch(err){
    console.log(err.message );
}
console.log("dskk");