try{
    console.log(a+b);
}
catch(err){
    console.log(err.message);
}